### ISSUE TITLE
error: class ‘tf::Transformer’ does not have any field named ‘tf2_buffer_’

### ISSUE THREAD

**Issue by ghost** [Serru/MultiCobot-UR10-Gripper#1]
When I compile the file I am facing the following problem. How Can I Solve?

![Screenshot from 2023-03-16 15-14-54](https://user-images.githubusercontent.com/101570598/225663239-b460db41-1714-4a04-9c26-50dcf8dc77bc.png)

**Comment by Serru** [comment]
Hello @Cansu3606,

Sorry for the late answer.

It looks like the problem could be a third party package, did you install all the packages?

I will write all the requirements step by step, then  you can make a check and see if you have everything installed so we can try to look into the problem parting from there.

---

## System requirements:
- SO: Ubuntu 16.04.7 LTS
- GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
- cmake: cmake version 3.12.4

---

## Requirements for ROS Kinetic
$ sudo sh -c "echo \"deb http://packages.ros.org/ros/ubuntu lsb_release -sc main\" > /etc/apt/sources.list.d/ros-latest.list"

$ sudo apt install curl

$ curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
$ sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654

$ sudo apt-get update -qq
$ sudo apt-get install dpkg

$ sudo apt-get install ros-kinetic-desktop-full

$ sudo apt install python-rosdep python-rosinstall python-rosinstall-generator python-wstool build-essential python-catkin-pkg ros-kinetic-ros-base

$ source /opt/ros/kinetic/setup.bash
$ sudo rosdep init
$ rosdep update

$ sudo apt install libprotobuf-dev protobuf-compiler python-pymodbus
$ sudo apt-get install ros-kinetic-moveit-ros-planning ros-kinetic-moveit-kinematics
$ sudo apt-get install ros-kinetic-moveit-simple-controller-manager ros-kinetic-position-controllers
$ sudo apt-get install ros-kinetic-moveit-fake-controller-manager ros-kinetic-gazebo-ros-control
$ sudo apt-get install ros-kinetic-joint-trajectory-controller ros-kinetic-moveit-ros-visualization
$ sudo apt-get install ros-kinetic-moveit-planners-ompl ros-kinetic-joint-state-controller
$ sudo apt-get install ros-kinetic-effort-controllers ros-kinetic-ros-controllers
$ sudo apt-get install ros-kinetic-industrial-msgs ros-kinetic-leap-motion

$ export PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages:/usr/local/lib/python2.7/dist-packages

---

## Installation of this repository
$ cd ~
$ git clone https://github.com/Serru/MultiCobot-UR10-Gripper

### Set the catkin workspace
$ cd ~/MultiCobot-UR10-Gripper/src
$ catkin_init_workspace

### Install all the dependencies
$ source /opt/ros/kinetic/setup.bash
$ cd ~/MultiCobot-UR10-Gripper
$ rospack profile
$ rosdep update
$ rosdep install -r -y --from-paths src --ignore-src --rosdistro kinetic

### Build the repository
$ catkin_make
$ rospack profile
$ source devel/setup.bash

### [optional] For maintaining a workspace of projects from multiple version-control systems
$ cd ~/MultiCobot-UR10-Gripper/src
$ wstool init
$ wstool up

---

### Run an example: Gazebo with two robots doing a simple Pick & Place
$ cd ~/MultiCobot-UR10-Gripper
$ catkin_make
$ source devel/setup.bash
$ rospack profile

# Terminal 1
$ cd ~/MultiCobot-UR10-Gripper
$ source devel/setup.bash
$ roslaunch two_arm_no_moveit_gazebo ur10_joint_limited.launch

# Terminal 2
$ cd ~/MultiCobot-UR10-Gripper
$ source devel/setup.bash
$ rosrun two_arm_no_moveit_manipulator ur10_1_robot_manipulator.py

# Terminal 3
$ cd ~/MultiCobot-UR10-Gripper
$ source devel/setup.bash
$ rosrun two_arm_no_moveit_manipulator ur10_2_robot_manipulator.py

---

I hope this is usefull for you and if this solves the problem, let me know so I can mark this issue as solved.

Best regards,

Mike.

**Comment by ghost** [comment]
Thank you for getting back to me. 

I am using Ubuntu 20.04.6 LTS. 

I applied all steps without error. When I made catkin, some errors occur. And, the problem is the Boost library. I downloaded it. But still, there are errors. I am sharing the screenshot. 

![Screenshot from 2023-03-20 09-20-52](https://user-images.githubusercontent.com/101570598/226298971-aa0113bb-0a1f-4ff4-9060-db0977116f0a.png)

I would greatly appreciate it if you could help me fix this.

**Comment by Serru** [comment]
Hello @Cansu3606,

I understand that you are trying to use a ROS Kinetic repository with ROS Noetic. Unfortunately, I can't guarantee that it will work for you, as the repository is designed specifically for ROS Kinetic, which runs on Ubuntu 16.04.

This is just the first problem you may encounter, and as you resolve each issue, you will likely find others. One of the strengths and weaknesses of ROS is its adaptability to new operating systems, which can sometimes result in incompatibilities with older versions. Given the time-consuming nature of the task, I'm afraid I can't provide much assistance in this case.

**The core problems you may encounter** when trying to adapt ROS Noetic to work with the repository code include:

- Some packages may be available, but their versions are not compatible. To resolve this, you would need to install the package and modify the source code yourself to make it compatible with ROS Kinetic, which is not time-efficient.

- Some packages are designed only for ROS Kinetic and are no longer available for later versions. In this case, you would need to download the Kinetic version and adapt it for ROS Noetic.

As I cannot provide much assistance, **I recommend considering the following solutions**:

- If ROS Noetic is not a strict requirement, you can create a partition on your computer or use a virtual machine to install Ubuntu 16.04 and run the repository on that system.

- You can download the repository code (and documentation) and use it as a reference to adapt it for ROS Noetic. You will need to understand the problems and look for similar packages that perform the same functions. Keep in mind that you will be responsible for configuring the system on your own, as I do not have time to update the repository to a newer version at the moment.

I apologize for not being able to help you more with this issue.

Best regards,

Mike.

[_Edited to make it clearer_]
